<template>
  <view class="dz-page dz-page--tabbed profile-page"><view class="dz-safe-top"/><main class="dz-container"><header class="profile-head"><view class="avatar"><image v-if="data?.avatar_url" :src="data.avatar_url" mode="aspectFill"/><text v-else>{{(data?.nickname||'达').slice(0,1)}}</text></view><view><strong class="strong-text">{{data?.nickname||'达人'}}</strong><text>已认证 · {{data?.service_city_name||'服务城市未设置'}}</text></view></header><section class="status-strip"><view><i :class="{online:data?.is_online}"/><text>{{data?.is_online?'在线接单中':'当前离线'}}</text></view><strong class="strong-text">信用良好</strong></section><h2>常用管理</h2><section class="entries"><button v-for="entry in entries" :key="entry.path" @tap="open(entry.path)"><view class="entry-icon"><image :src="entry.icon" mode="aspectFit"/></view><view><strong class="strong-text">{{entry.label}}</strong><text>{{entry.copy}}</text></view><b>›</b></button></section><button class="logout" @tap="signOut">退出登录</button></main><ProviderTabBar active="profile"/></view>
</template>
<script setup lang="ts">
import {ref} from 'vue';import{onShow}from'@dcloudio/uni-app';import ProviderTabBar from '@/components/ProviderTabBar.vue';import{logout}from '@/services/auth';import{stopLocationReporting}from '@/services/locationReporter';import{getProviderWorkbench,stopProviderOnline}from '@/services/providers';import type{ProviderWorkbench}from '@/types/api';
const data=ref<ProviderWorkbench|null>(null);const entries=[{label:'服务管理',copy:'服务项目、价格和上架状态',path:'/pages/services/index',icon:'/static/icons/service.svg'},{label:'档期管理',copy:'设置可服务时段和休息日',path:'/pages/schedule/index',icon:'/static/icons/schedule.svg'},{label:'达人订单',copy:'接单、出发和服务履约',path:'/pages/orders/index',icon:'/static/icons/orders.svg'},{label:'收入明细',copy:'本月经营与结算记录',path:'/pages/income/index',icon:'/static/icons/income.svg'}];
function open(path:string){uni.navigateTo({url:path})}async function signOut(){uni.showModal({title:'退出登录',content:data.value?.is_online?'退出后将同时停止在线接单，确定继续吗？':'确定退出达人工作端吗？',success:async result=>{if(!result.confirm)return;try{if(data.value?.is_online)await stopProviderOnline()}catch{}stopLocationReporting();await logout();uni.reLaunch({url:'/pages/auth/login'})}})}onShow(async()=>{try{data.value=(await getProviderWorkbench()).data}catch{}})
</script>
<style lang="scss" scoped>@use '../../styles/tokens.scss' as *;.profile-page{background:linear-gradient(180deg,#eafafa 0,#fff 360rpx,#f8fbfb 100%)}.profile-head{display:flex;align-items:center;padding:48rpx 8rpx 34rpx}.avatar{display:flex;overflow:hidden;width:116rpx;height:116rpx;align-items:center;justify-content:center;border:5rpx solid #fff;border-radius:50%;color:$dz-brand-deep;background:$dz-brand-soft;box-shadow:$dz-shadow-soft;font-size:38rpx}.avatar image{width:100%;height:100%}.profile-head>view:last-child{display:flex;gap:10rpx;margin-left:23rpx;flex-direction:column}.profile-head .strong-text{font-size:36rpx}.profile-head text{color:$dz-text-secondary;font-size:20rpx}.status-strip{display:flex;height:88rpx;align-items:center;justify-content:space-between;padding:0 25rpx;border:1rpx solid #d7eeee;border-radius:25rpx;background:#fff;box-shadow:$dz-shadow-soft}.status-strip view{display:flex;align-items:center}.status-strip i{width:15rpx;height:15rpx;margin-right:11rpx;border-radius:50%;background:#aab5b7}.status-strip i.online{background:$dz-online;box-shadow:0 0 0 8rpx rgba(32,184,108,.1)}.status-strip text{font-size:22rpx}.status-strip .strong-text{color:$dz-brand-deep;font-size:20rpx}.profile-page h2{margin:34rpx 4rpx 19rpx;font-size:27rpx}.entries{overflow:hidden;border:1rpx solid $dz-border;border-radius:28rpx;background:#fff;box-shadow:$dz-shadow}.entries button{display:flex;width:100%;min-height:112rpx;align-items:center;margin:0;padding:18rpx 24rpx;border:0;border-bottom:1rpx solid $dz-border;background:#fff;text-align:left}.entries button:last-child{border-bottom:0}.entry-icon{display:flex;width:64rpx;height:64rpx;align-items:center;justify-content:center;border-radius:18rpx;background:$dz-brand-pale}.entry-icon image{width:40rpx;height:40rpx}.entries button>view:nth-child(2){display:flex;min-width:0;gap:7rpx;margin-left:19rpx;flex:1;flex-direction:column}.entries .strong-text{font-size:24rpx}.entries text{color:$dz-text-secondary;font-size:18rpx}.entries b{color:$dz-text-tertiary;font-size:36rpx;font-weight:400}.logout{height:78rpx;margin:32rpx 0;border:1rpx solid #ffcfd1;border-radius:39rpx;color:$dz-danger;background:#fff;font-size:23rpx;line-height:78rpx}</style>
