<template>
  <view class="dz-page profile-edit-page"><view class="dz-safe-top"/><header class="page-nav dz-container"><button @tap="back">‹</button><strong>达人资料</strong><view/></header><main class="dz-container">
    <NetworkState v-if="loading" loading message="正在加载达人资料…"/><NetworkState v-else-if="error" :message="error" action-text="重新加载" @action="load"/>
    <template v-else-if="data"><section class="intro"><strong>完善你的公开资料</strong><text>生活照、简介和服务城市会用于达人主页展示与服务匹配。</text></section><section class="form-card">
      <view class="photo-row"><image v-if="preview" :src="preview" mode="aspectFill"/><view v-else class="photo-empty">＋</view><view><strong>生活照</strong><text>清晰自然的半身或全身照</text></view><button :disabled="uploading" @tap="choosePhoto">{{preview?'更换':'上传'}}</button></view>
      <label><text>达人简介</text><textarea v-model="form.bio" maxlength="500" placeholder="介绍你的特长、性格和服务体验（至少10字）"/><small>{{form.bio.length}}/500</small></label>
      <view class="row"><text>服务城市</text><picker :range="cities" range-key="name" @change="chooseCity"><view>{{form.service_city_name||'请选择'}} ›</view></picker></view>
      <view class="radius"><view><text>最大接单半径</text><strong>{{form.max_service_radius_km}}km</strong></view><slider :value="form.max_service_radius_km" min="10" max="70" activeColor="#11c1c4" block-size="20" @change="changeRadius"/></view>
    </section><button class="save" :disabled="saving||uploading" @tap="save">{{saving?'保存中…':'保存资料'}}</button></template>
  </main></view>
</template>
<script setup lang="ts">
import{reactive,ref,shallowRef}from'vue';import{onLoad}from'@dcloudio/uni-app';import NetworkState from '@/components/NetworkState.vue';import{getProviderProfile,saveProviderProfile,uploadProviderLifestylePhoto}from'@/services/providers';import type{ProviderProfileData}from'@/types/api';import{getErrorMessage}from'@/utils/formatters';
const cities=[{code:'130400',name:'邯郸市'},{code:'110100',name:'北京市'},{code:'310100',name:'上海市'}];const loading=ref(true),saving=ref(false),uploading=ref(false),error=ref(''),preview=ref(''),filePath=ref('');const file=shallowRef<unknown>();const data=ref<ProviderProfileData|null>(null);const form=reactive({bio:'',lifestyle_photo_id:null as string|null,service_city_code:'130400',service_city_name:'邯郸市',max_service_radius_km:10});function back(){uni.navigateBack()}function apply(value:ProviderProfileData){data.value=value;Object.assign(form,{bio:value.bio,lifestyle_photo_id:value.lifestyle_photo_id,service_city_code:value.service_city_code||'130400',service_city_name:value.service_city_name||'邯郸市',max_service_radius_km:value.max_service_radius_km});preview.value=value.lifestyle_photo_url||''}async function load(){loading.value=true;error.value='';try{apply((await getProviderProfile()).data)}catch(reason){error.value=getErrorMessage(reason)}finally{loading.value=false}}function chooseCity(event:{detail:{value:string}}){const city=cities[Number(event.detail.value)];if(city){form.service_city_code=city.code;form.service_city_name=city.name}}function changeRadius(event:{detail:{value:number}}){form.max_service_radius_km=Number(event.detail.value)}function choosePhoto(){uni.chooseImage({count:1,sizeType:['compressed'],sourceType:['album','camera'],success:({tempFilePaths,tempFiles})=>{const selected=Array.isArray(tempFiles)?tempFiles[0]:tempFiles;if(selected?.size&&selected.size>8*1024*1024)return uni.showToast({title:'生活照不能超过8MB',icon:'none'});filePath.value=tempFilePaths[0];file.value=selected;preview.value=tempFilePaths[0]}})}async function save(){if(form.bio.trim().length<10)return uni.showToast({title:'达人简介至少10个字',icon:'none'});saving.value=true;try{if(filePath.value){uploading.value=true;const uploaded=await uploadProviderLifestylePhoto(filePath.value,file.value);form.lifestyle_photo_id=uploaded.data.id;uploading.value=false}apply((await saveProviderProfile({...form,bio:form.bio.trim()})).data);filePath.value='';file.value=undefined;uni.showToast({title:'资料已保存',icon:'success'})}catch(reason){uni.showToast({title:getErrorMessage(reason),icon:'none'})}finally{saving.value=false;uploading.value=false}}onLoad(load)
</script>
<style lang="scss" scoped>@use '../../styles/tokens.scss' as *;.profile-edit-page{background:linear-gradient(180deg,#eafafa 0,#f8fbfb 400rpx)}.page-nav{display:flex;height:88rpx;align-items:center;justify-content:space-between}.page-nav button,.page-nav>view{width:64rpx}.page-nav button{height:64rpx;margin:0;padding:0;border:0;background:transparent;font-size:52rpx;line-height:58rpx}.page-nav strong{font-size:30rpx}.intro{display:flex;gap:10rpx;padding:24rpx 4rpx;flex-direction:column}.intro strong{font-size:29rpx}.intro text{color:$dz-text-secondary;font-size:20rpx}.form-card{overflow:hidden;border:1rpx solid $dz-border;border-radius:27rpx;background:#fff;box-shadow:$dz-shadow}.photo-row{display:flex;min-height:150rpx;align-items:center;padding:22rpx 24rpx;border-bottom:1rpx solid $dz-border}.photo-row image,.photo-empty{display:flex;width:112rpx;height:112rpx;flex:none;align-items:center;justify-content:center;border-radius:18rpx;color:$dz-brand;background:$dz-brand-pale;font-size:38rpx}.photo-row>view:nth-child(2){display:flex;min-width:0;gap:8rpx;margin-left:18rpx;flex:1;flex-direction:column}.photo-row strong{font-size:23rpx}.photo-row text{color:$dz-text-secondary;font-size:18rpx}.photo-row button{height:58rpx;margin:0;padding:0 22rpx;border:1rpx solid $dz-brand;border-radius:29rpx;color:$dz-brand;background:#fff;font-size:19rpx;line-height:58rpx}.form-card label,.row,.radius{display:block;padding:24rpx;border-bottom:1rpx solid $dz-border}.form-card> :last-child{border-bottom:0}.form-card label>text,.row>text,.radius>view>text{font-size:23rpx;font-weight:700}.form-card textarea{width:100%;height:150rpx;margin-top:15rpx;font-size:22rpx;line-height:1.55}.form-card small{display:block;color:$dz-text-tertiary;text-align:right;font-size:18rpx}.row{display:flex;align-items:center;justify-content:space-between}.row picker{color:$dz-text-secondary;font-size:22rpx}.radius>view{display:flex;justify-content:space-between}.radius strong{color:$dz-brand;font-size:23rpx}.radius slider{margin:18rpx 0 0}.save{height:84rpx;margin:28rpx 0 calc(30rpx + env(safe-area-inset-bottom));border:0;border-radius:42rpx;color:#fff;background:$dz-gradient-brand;font-size:25rpx;line-height:84rpx}</style>
